### PR TITLE
Remove polyfill for JSON

### PR DESCRIPTION
**Pull request by tenorok**
After research became know that for functions `JSON.stringify()` and `JSON.parse()` all popular browsers including IE8 already have native realisation.
For this reason we can remove polyfills for JSON.

### CODE REVIEW

**Comment by dfilatov** [comment]
Requires document to be in IE8+ standards mode to work in IE8. But afaik at Yandex we don't use this mode, so these functions won't work.

**Comment by narqo** [comment]
@dfilatov AFAIK, all our services (at least those who use `lego/islands*`) already have switched to standard mode in IE

**Comment by tadatuta** [comment]
some time ago there was [an issue](https://nda.ya.ru/3QgPpM) with MS compatibility list where `yandex.ru` was forced to render in quirks. not sure if it's still so.

**Comment by narqo** [comment]
@tenorok @tadatuta should I wait for research results about compatibility list?

**Comment by tenorok** [comment]
What are you talking about?
Can i use? http://caniuse.com/#search=JSON

**Comment by tadatuta** [comment]
@tenorok refer notes:
> Requires document to be in IE8+ standards mode to work in IE8.

**Comment by mishaberezin** [comment]
I almost sure no one uses islands-* or bem-* with IE8 not switched to standards mode. But if there is a small chance to break something, we would better leave it as is.

**Pull request closed without merging**
